# example/a               // project full path
#  target: esp32          // target name
#  sdkconfig:             // sdkconfig name
#     - a                 // sdkconfig.ci.a
#     - default           // sdkconfig.default (will be renamed to {target}_generic)
#  target: esp32s3        // target name
#  sdkconfig:             // sdkconfig name
#     - b                 // sdkconfig.ci.b
#     - default           // sdkconfig.default (will be renamed to {target}_generic)
#  description:           // Description of the example (optional)
#     <description>
#  readme:                // readme url must point a README.md link (optional)
#     <URL>

examples/keyboard:
  esp32s3:
    sdkconfig:
      - defaults
  description: A full key anti-ghosting keyboard powered by the ESP32S3. https://github.com/espressif/esp-iot-solution/tree/master/examples/keyboard
  readme: https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/keyboard/README.md

examples/usb/device/usb_dual_uvc_device:
  esp32s3:
    sdkconfig:
      - esp32s3_usb_otg
      - defaults
  esp32p4:
    sdkconfig:
      - defaults
  description:
    This is the USB dual UVC device example
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/device/usb_dual_uvc_device/README.md

examples/usb/device/usb_webcam:
  esp32s3:
    sdkconfig:
      - esp32s3_eye
  description:
    This is the USB webcam example
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/device/usb_webcam/README.md

examples/usb/host/usb_camera_lcd_display:
  esp32s3:
    sdkconfig:
      - esp32s3_lcd_ev_board
  description:
    This is the USB camera LCD display example
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/host/usb_camera_lcd_display/README.md

examples/usb/host/usb_camera_mic_spk:
  esp32s3:
    sdkconfig:
      - esp32s3_usb_otg
      - defaults
  description:
    This is the USB camera microphone speaker example
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/host/usb_camera_mic_spk/README.md

examples/usb/host/usb_cdc_4g_module:
  esp32s3:
    sdkconfig:
      - esp32s3_usb_otg
      - defaults
  description:
    This is the USB CDC 4G module example
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/host/usb_cdc_4g_module/README.md

examples/usb/host/usb_cdc_basic:
  esp32s3:
    sdkconfig:
      - esp32s3_usb_otg
  description:
    This is the USB CDC basic example
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/host/sb_cdc_basic/README.md
